# -*- coding: utf-8 -*-
"""thi_giua_ky.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zHJAZfwJNFmKVH1e0LV9-0WX-KWd_gfw
"""

#cau 2a
string = input()
str = string.split(" ")
 
count={}
for i in str:
    if i in count:
        count[i]+=1
    else:
        count[i]=1
 
for i in sorted(count, key=count.get, reverse=False):
       print(i, count[i])

#cau3a
dict = {1:'red', 2:'blue', 3:'yellow'}
keys_sorted1 = sorted(dict, reverse=True)
print(keys_sorted1)

#cau3b
dict_a = [{'name': 'python', 'points': 10}, {'name': 'java', 'points': 8}]
point = map(lambda x: x['points'] * 10, dict_a) 
print(list(point))

#cau2b
def xoa_trung_lap(s):
   chuoiKetQua = "cảm ơn"
   for kyTu in s:
       if kyTu not in chuoiKetQua:
           chuoiKetQua 
   return chuoiKetQua
s = input()
print(xoa_trung_lap(s))