# -*- coding: utf-8 -*-
"""THT2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vna3fQWJlwqD_-trYD43uRJT6tKp89yF
"""

#@title BT14
def scalar_multi (a,b):
  s=0
  for i in range(len(a)):
    s+=a[i]+b[i]
  return s
a=input().split()
b=input().split()
for i in range(len(a)):
  a[i]=int(a[i])
  b[i]=int(b[i])
print('tong 2 vector la: ', scalar_multi(a,b))

#@title BT17
def so_nho_nhat(danhSachSo):
   soNhoNhat = danhSachSo[0]
   for so in danhSachSo:
       if so < soNhoNhat:
           soNhoNhat = so
   return soNhoNhat
def so_lon_nhat(danhSachSo):
   soLonNhat = danhSachSo[0]
   for so in danhSachSo:
       if so > soLonNhat:
           soLonNhat = so
   return soLonNhat
danhSach = [1, 2, 3, 4, 5, 6, -6, -5, -4, -3, -2, -1, 0]
if len(danhSach) == 0:
   print("Danh sach rong")
else:
   try:       
       danhSachSo = list(map(float, danhSach))
       soNhoNhat = so_nho_nhat(danhSachSo)
       soLonNhat = so_lon_nhat(danhSachSo)
       print('Phần tử có giá trị lớn nhất',soLonNhat)
       print('Phần tử có giá trị nhỏ nhất',soNhoNhat)
   except:
       print("Vui long nhap cac phan tu la so thuc!")

def norm(vector):
    return sqrt(sum(x * x for x in vector))    
 
def cosine_similarity(vec_a, vec_b):
        norm_a = norm(vec_a)
        norm_b = norm(vec_b)
        dot = sum(a * b for a, b in zip(vec_a, vec_b))
        return dot / (norm_a * norm_b)